[build]
publish = "public"
command = "node scripts/generate-file-data.js"

[[redirects]]
from = "/files/*"
to = "/files/:splat"
status = 200

# 重定向脚本文件
[[redirects]]
from = "/scripts/*"
to = "/scripts/:splat"
status = 200

[[redirects]]
from = "/*"
to = "public/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET,HEAD,OPTIONS"
Access-Control-Allow-Headers = "*"
